# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sat_descrip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sat_descrip.proto',
  package='LEOHack',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11sat_descrip.proto\x12\x07LEOHack\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"-\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"2\n\x07Twist2D\x12\x0b\n\x03v_x\x18\x01 \x01(\x02\x12\x0b\n\x03v_y\x18\x02 \x01(\x02\x12\r\n\x05omega\x18\x03 \x01(\x02\"1\n\x08Wrench2D\x12\x0b\n\x03\x66_x\x18\x01 \x01(\x02\x12\x0b\n\x03\x66_y\x18\x02 \x01(\x02\x12\x0b\n\x03tau\x18\x03 \x01(\x02\",\n\x08TeamInfo\x12\x10\n\x08teamName\x18\x01 \x01(\t\x12\x0e\n\x06teamID\x18\x02 \x01(\r\"m\n\x14SatelliteDescription\x12#\n\x08teamInfo\x18\x01 \x01(\x0b\x32\x11.LEOHack.TeamInfo\x12\x0c\n\x04mass\x18\x02 \x01(\x02\x12\x0f\n\x07inertia\x18\x03 \x01(\x02\x12\x11\n\tipAddress\x18\x05 \x01(\t\"]\n\rSataliteState\x12\x1d\n\x04pose\x18\x03 \x01(\x0b\x32\x0f.LEOHack.Pose2D\x12\x1f\n\x05twist\x18\x04 \x01(\x0b\x32\x10.LEOHack.Twist2D\x12\x0c\n\x04\x66uel\x18\x05 \x01(\x02\"\xcc\x01\n\x0bSystemState\x12)\n\x05state\x18\x01 \x01(\x0e\x32\x1a.LEOHack.SystemState.State\x12.\n\x0b\x65lapsedTime\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x30\n\x0c\x61\x62soluteTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"0\n\x05State\x12\x08\n\x04INIT\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\t\n\x05RESET\x10\x02\x12\t\n\x05\x41\x42ORT\x10\x03\"~\n\x0e\x43ontrolMessage\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12!\n\x06thrust\x18\x02 \x01(\x0b\x32\x11.LEOHack.Wrench2D\x12&\n\rabsolute_pose\x18\x03 \x01(\x0b\x32\x0f.LEOHack.Pose2D\x12\x11\n\ttime_step\x18\x04 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])



_SYSTEMSTATE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='LEOHack.SystemState.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABORT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=654,
  serialized_end=702,
)
_sym_db.RegisterEnumDescriptor(_SYSTEMSTATE_STATE)


_POSE2D = _descriptor.Descriptor(
  name='Pose2D',
  full_name='LEOHack.Pose2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='LEOHack.Pose2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='LEOHack.Pose2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='LEOHack.Pose2D.theta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=140,
)


_TWIST2D = _descriptor.Descriptor(
  name='Twist2D',
  full_name='LEOHack.Twist2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v_x', full_name='LEOHack.Twist2D.v_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_y', full_name='LEOHack.Twist2D.v_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='omega', full_name='LEOHack.Twist2D.omega', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=192,
)


_WRENCH2D = _descriptor.Descriptor(
  name='Wrench2D',
  full_name='LEOHack.Wrench2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f_x', full_name='LEOHack.Wrench2D.f_x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f_y', full_name='LEOHack.Wrench2D.f_y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tau', full_name='LEOHack.Wrench2D.tau', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=243,
)


_TEAMINFO = _descriptor.Descriptor(
  name='TeamInfo',
  full_name='LEOHack.TeamInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teamName', full_name='LEOHack.TeamInfo.teamName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teamID', full_name='LEOHack.TeamInfo.teamID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=289,
)


_SATELLITEDESCRIPTION = _descriptor.Descriptor(
  name='SatelliteDescription',
  full_name='LEOHack.SatelliteDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teamInfo', full_name='LEOHack.SatelliteDescription.teamInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='LEOHack.SatelliteDescription.mass', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inertia', full_name='LEOHack.SatelliteDescription.inertia', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipAddress', full_name='LEOHack.SatelliteDescription.ipAddress', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=400,
)


_SATALITESTATE = _descriptor.Descriptor(
  name='SataliteState',
  full_name='LEOHack.SataliteState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='LEOHack.SataliteState.pose', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twist', full_name='LEOHack.SataliteState.twist', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fuel', full_name='LEOHack.SataliteState.fuel', index=2,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=495,
)


_SYSTEMSTATE = _descriptor.Descriptor(
  name='SystemState',
  full_name='LEOHack.SystemState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='LEOHack.SystemState.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsedTime', full_name='LEOHack.SystemState.elapsedTime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='absoluteTime', full_name='LEOHack.SystemState.absoluteTime', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYSTEMSTATE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=702,
)


_CONTROLMESSAGE = _descriptor.Descriptor(
  name='ControlMessage',
  full_name='LEOHack.ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='LEOHack.ControlMessage.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thrust', full_name='LEOHack.ControlMessage.thrust', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='absolute_pose', full_name='LEOHack.ControlMessage.absolute_pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_step', full_name='LEOHack.ControlMessage.time_step', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=704,
  serialized_end=830,
)

_SATELLITEDESCRIPTION.fields_by_name['teamInfo'].message_type = _TEAMINFO
_SATALITESTATE.fields_by_name['pose'].message_type = _POSE2D
_SATALITESTATE.fields_by_name['twist'].message_type = _TWIST2D
_SYSTEMSTATE.fields_by_name['state'].enum_type = _SYSTEMSTATE_STATE
_SYSTEMSTATE.fields_by_name['elapsedTime'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_SYSTEMSTATE.fields_by_name['absoluteTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SYSTEMSTATE_STATE.containing_type = _SYSTEMSTATE
_CONTROLMESSAGE.fields_by_name['thrust'].message_type = _WRENCH2D
_CONTROLMESSAGE.fields_by_name['absolute_pose'].message_type = _POSE2D
DESCRIPTOR.message_types_by_name['Pose2D'] = _POSE2D
DESCRIPTOR.message_types_by_name['Twist2D'] = _TWIST2D
DESCRIPTOR.message_types_by_name['Wrench2D'] = _WRENCH2D
DESCRIPTOR.message_types_by_name['TeamInfo'] = _TEAMINFO
DESCRIPTOR.message_types_by_name['SatelliteDescription'] = _SATELLITEDESCRIPTION
DESCRIPTOR.message_types_by_name['SataliteState'] = _SATALITESTATE
DESCRIPTOR.message_types_by_name['SystemState'] = _SYSTEMSTATE
DESCRIPTOR.message_types_by_name['ControlMessage'] = _CONTROLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose2D = _reflection.GeneratedProtocolMessageType('Pose2D', (_message.Message,), dict(
  DESCRIPTOR = _POSE2D,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.Pose2D)
  ))
_sym_db.RegisterMessage(Pose2D)

Twist2D = _reflection.GeneratedProtocolMessageType('Twist2D', (_message.Message,), dict(
  DESCRIPTOR = _TWIST2D,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.Twist2D)
  ))
_sym_db.RegisterMessage(Twist2D)

Wrench2D = _reflection.GeneratedProtocolMessageType('Wrench2D', (_message.Message,), dict(
  DESCRIPTOR = _WRENCH2D,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.Wrench2D)
  ))
_sym_db.RegisterMessage(Wrench2D)

TeamInfo = _reflection.GeneratedProtocolMessageType('TeamInfo', (_message.Message,), dict(
  DESCRIPTOR = _TEAMINFO,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.TeamInfo)
  ))
_sym_db.RegisterMessage(TeamInfo)

SatelliteDescription = _reflection.GeneratedProtocolMessageType('SatelliteDescription', (_message.Message,), dict(
  DESCRIPTOR = _SATELLITEDESCRIPTION,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.SatelliteDescription)
  ))
_sym_db.RegisterMessage(SatelliteDescription)

SataliteState = _reflection.GeneratedProtocolMessageType('SataliteState', (_message.Message,), dict(
  DESCRIPTOR = _SATALITESTATE,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.SataliteState)
  ))
_sym_db.RegisterMessage(SataliteState)

SystemState = _reflection.GeneratedProtocolMessageType('SystemState', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMSTATE,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.SystemState)
  ))
_sym_db.RegisterMessage(SystemState)

ControlMessage = _reflection.GeneratedProtocolMessageType('ControlMessage', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLMESSAGE,
  __module__ = 'sat_descrip_pb2'
  # @@protoc_insertion_point(class_scope:LEOHack.ControlMessage)
  ))
_sym_db.RegisterMessage(ControlMessage)


# @@protoc_insertion_point(module_scope)
