M48
; DRILL file {KiCad (6.0.0)} date Sun Jan  2 23:15:29 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-02T23:15:29+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X99.575Y-65.03
X104.425Y-65.03
T2
X99.275Y-62.0
X104.725Y-62.0
T0
M30
